version: "3"

services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto:latest
    ports:
      - 8081:1883
    volumes:
      - "./mosquitto.conf:/mosquitto/config/mosquitto.conf"

    networks:
      - mqtt-network



networks:
  mqtt-network:
    name: mqtt-network
    driver: bridge
